# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2017-05-16 13:27+0300\n"
"PO-Revision-Date: 2017-05-16 14:42+0300\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.7.1\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"Language: ru\n"

#: VM/BDL/BDCon.py:19 VM/UI/ChoosingItem.py:35
msgid "There are no items to sell"
msgstr "Нет предметов к продаже"

#: VM/BDL/BDCon.py:20 VM/UI/ChoosingItem.py:36
msgid "Message"
msgstr "Сообщение"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:76
#: VM/BDL/DataSources/MySQLDB.py:91 VM/BDL/DataSources/MySQLDB.py:107
#: VM/BDL/DataSources/MySQLDB.py:123 VM/BDL/DataSources/MySQLDB.py:178
#: VM/Printer/PrnDK350.py:34 VM/Vending.py:40
msgid "Error"
msgstr "Ошибка"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:91
#: VM/BDL/DataSources/MySQLDB.py:107 VM/BDL/DataSources/MySQLDB.py:123
msgid "Database connection failed"
msgstr "Ошибка соединения с базой данных"

#: VM/BDL/DataSources/MySQLDB.py:76
msgid "There is errors in the configuration file. No section."
msgstr "Ошибка в файле конфигурации. Отсутствует секция."

#: VM/BDL/DataSources/MySQLDB.py:178
msgid "Database error"
msgstr "Ошибка базы данных."

#: VM/Errors.py:15
msgid "Close"
msgstr "Закрыть"

#: VM/KP/KPProvider.py:90
msgid "Error in recognition of note"
msgstr "Банкнота не опознана"

#: VM/KP/KPProvider.py:104
msgid "Protocol version's setting error"
msgstr "Ошибка установки версии протокола"

#: VM/KP/KPProvider.py:111
msgid "Error in request of notes' channels"
msgstr "Ошибка запроса канала банкноты"

#: VM/KP/KPProvider.py:120
msgid "Error in notes' denomination reading"
msgstr "Ошибка чтения номинала банкноты"

#: VM/KP/KPProvider.py:127
msgid "Error in setting channels of notes receiving"
msgstr "Ошибка установки канала приема банкноты"

#: VM/KP/KPProvider.py:134
msgid "Engage procedure error"
msgstr "Ошибка процедуры запуска"

#: VM/KP/KPProvider.py:149
msgid "Device synchronization failed"
msgstr "Ошибка синхронизации устройства"

#: VM/KP/KPProvider.py:281
msgid "Note receiver's port is not found"
msgstr "Порт купюроприемника не найден"

#: VM/KP/KPProvider.py:295
msgid "Devise not responding"
msgstr "Устройство не отвечает"

#: VM/Printer/PrnDK350.py:34
msgid "Configuration file error. No printer's section."
msgstr "Ошибка файла конфигурации. Отсутствует секция принтера."

#: VM/UI/ChoosingItem.py:85
msgid "Select the model"
msgstr "Выберите модель"

#: VM/UI/FinishWindow.py:26
msgid "The key was written successfully"
msgstr "Ключ записан успешно"

#: VM/UI/FinishWindow.py:27
msgid "Thanks for purchase"
msgstr "Благодарим за покупку"

#: VM/UI/GivingOutItem.py:19
msgid "Wait for delivery..."
msgstr "Ожидайте выдачи..."

#: VM/UI/GivingOutItem.py:25
msgid "Delivery error. Call techsupport, please."
msgstr "Ошибка выдачи. Обратитесь в техподдержку."

#: VM/UI/ReceiveCash.py:34
msgid "Incomming cash"
msgstr "Внесенная сумма"

#: VM/UI/ReceiveCash.py:35
msgid "Pay"
msgstr "Оплатить"

#: VM/UI/ReceiveCash.py:36
msgid "Mashine does not give any odd money"
msgstr "Внимание! Аппарат сдачи не дает."

#: VM/UI/ReceiveCash.py:37
msgid "Cancel"
msgstr "Отмена"

#: VM/UI/ReceiveCash.py:38 VM/UI/WriteBrelok.py:34
msgid "Next"
msgstr "Далее"

#: VM/UI/ScanBrelok.py:57
msgid "Press the button \"Scan\""
msgstr "Нажмите кнопку \"Сканировать\""

#: VM/UI/ScanBrelok.py:58
msgid "and enclose your key to the scanner"
msgstr "и поднесите ключ к сканнеру"

#: VM/UI/ScanBrelok.py:59
msgid "Scanning..."
msgstr "Сканирование..."

#: VM/UI/ScanBrelok.py:60
msgid "Scanning failed"
msgstr "Ошибка сканирования"

#: VM/UI/ScanBrelok.py:61
msgid "Scan"
msgstr "Сканировать"

#: VM/UI/WriteBrelok.py:29
msgid "The key is given away"
msgstr "Ключ выдан"

#: VM/UI/WriteBrelok.py:30
msgid "Press 'Next'"
msgstr "Нажмите \"Далее\""

#: VM/UI/WriteBrelok.py:31
msgid "and enclose it to the scanner"
msgstr "и поднесите ключ к сканнеру"

#: VM/UI/WriteBrelok.py:32
msgid "Writing..."
msgstr "Запись..."

#: VM/UI/WriteBrelok.py:33
msgid "Writing failed. Try again, please."
msgstr "Запись неудачна. Попробуйте еще раз."

#: VM/Vending.py:39
msgid "Database connection error"
msgstr "Ошибка соединения с базой данных"
