# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: 2017-06-02 00:15+0300\n"
"PO-Revision-Date: 2017-06-02 00:19+0300\n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"
"X-Generator: Poedit 1.8.7.1\n"
"Last-Translator: \n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"Language: ru\n"

#: VM/BDL/BDCon.py:19 VM/UI/ChoosingItem.py:41
msgid "There are no items to sell"
msgstr "Нет предметов к продаже"

#: VM/BDL/BDCon.py:20 VM/UI/ChoosingItem.py:42
msgid "Message"
msgstr "Сообщение"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:76
#: VM/BDL/DataSources/MySQLDB.py:91 VM/BDL/DataSources/MySQLDB.py:107
#: VM/BDL/DataSources/MySQLDB.py:123 VM/BDL/DataSources/MySQLDB.py:178
#: VM/UI/CheckPass.py:31 VM/Vending.py:40
msgid "Error"
msgstr "Ошибка"

#: VM/BDL/DataSources/MySQLDB.py:60 VM/BDL/DataSources/MySQLDB.py:91
#: VM/BDL/DataSources/MySQLDB.py:107 VM/BDL/DataSources/MySQLDB.py:123
msgid "Database connection failed"
msgstr "Ошибка соединения с базой данных"

#: VM/BDL/DataSources/MySQLDB.py:76 VM/UI/CheckPass.py:31
msgid "There is errors in the configuration file. No section."
msgstr "Ошибка в файле конфигурации. Отсутствует секция."

#: VM/BDL/DataSources/MySQLDB.py:178
msgid "Database error"
msgstr "Ошибка базы данных."

#: VM/Errors.py:19
msgid "Close"
msgstr "Закрыть"

#: VM/KP/KPProvider.py:91
msgid "Error in recognition of note"
msgstr "Банкнота не опознана"

#: VM/KP/KPProvider.py:106
msgid "Protocol version's setting error"
msgstr "Ошибка установки версии протокола"

#: VM/KP/KPProvider.py:113
msgid "Error in request of notes' channels"
msgstr "Ошибка запроса канала банкноты"

#: VM/KP/KPProvider.py:122
msgid "Error in notes' denomination reading"
msgstr "Ошибка чтения номинала банкноты"

#: VM/KP/KPProvider.py:129
msgid "Error in setting channels of notes receiving"
msgstr "Ошибка установки канала приема банкноты"

#: VM/KP/KPProvider.py:136
msgid "Engage procedure error"
msgstr "Ошибка процедуры запуска"

#: VM/KP/KPProvider.py:151
msgid "Device synchronization failed"
msgstr "Ошибка синхронизации устройства"

#: VM/KP/KPProvider.py:288
msgid "Note receiver's port is not found"
msgstr "Порт купюроприемника не найден"

#: VM/KP/KPProvider.py:305
msgid "Devise not responding"
msgstr "Устройство не отвечает"

#: VM/UI/ChoosingItem.py:95
msgid "Select the model"
msgstr "Выберите модель"

#: VM/UI/ChoosingItem.py:96 VM/UI/ReceiveCash.py:50
msgid "Cancel"
msgstr "Отмена"

#: VM/UI/FinishWindow.py:33
msgid "The key was written successfully"
msgstr "Ключ записан успешно"

#: VM/UI/FinishWindow.py:34
msgid "Thanks for purchase"
msgstr "Благодарим за покупку"

#: VM/UI/GivingOutItem.py:29
msgid "Wait for delivery..."
msgstr "Ожидайте выдачи..."

#: VM/UI/GivingOutItem.py:36
msgid "Delivery error. Call techsupport, please."
msgstr "Ошибка выдачи. Обратитесь в техподдержку."

#: VM/UI/ReceiveCash.py:47
msgid "Incomming cash"
msgstr "Внесенная сумма"

#: VM/UI/ReceiveCash.py:48
msgid "Pay"
msgstr "Оплатить"

#: VM/UI/ReceiveCash.py:49
msgid "Mashine does not give any odd money"
msgstr "Внимание! Аппарат сдачи не дает."

#: VM/UI/ReceiveCash.py:51
msgid "Next"
msgstr "Далее"

#: VM/UI/ScanBrelok.py:70
msgid "Press the button \"Scan\""
msgstr "Нажмите кнопку \"Сканировать\""

#: VM/UI/ScanBrelok.py:71
msgid "and enclose your key"
msgstr "и поднесите ключ"

#: VM/UI/ScanBrelok.py:72
msgid "to the scanner"
msgstr "к сканнеру"

#: VM/UI/ScanBrelok.py:73
msgid "Scanning..."
msgstr "Сканирование..."

#: VM/UI/ScanBrelok.py:74
msgid "Error!"
msgstr "Ошибка!"

#: VM/UI/ScanBrelok.py:75
msgid "Scan"
msgstr "Сканировать"

#: VM/UI/WriteBrelok.py:40
msgid "The key is given away"
msgstr "Ключ выдан"

#: VM/UI/WriteBrelok.py:41
msgid "Press 'Next'"
msgstr "Нажмите \"Далее\""

#: VM/UI/WriteBrelok.py:42
msgid "and enclose it to the scanner"
msgstr "и поднесите ключ к сканнеру"

#: VM/UI/WriteBrelok.py:43
msgid "Writing..."
msgstr "Запись..."

#: VM/UI/WriteBrelok.py:44
msgid "Writing failed!"
msgstr "Ошибка записи!"

#: VM/UI/WriteBrelok.py:45
msgid "Try again, please."
msgstr "Попробуйте еще раз."

#: VM/UI/WriteBrelok.py:46
msgid "Write"
msgstr "Записать"

#: VM/Vending.py:39
msgid "Database connection error"
msgstr "Ошибка соединения с базой данных"
